<a href="https://colab.research.google.com/github/SirCarlitros/Math3/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7])

In [3]:
matrix01 = np.array([[1,2,3],[5,6,8],[9,10,11]])
matrix02 = np.array([[0,0,0],[2,2,2],[1,1,1]])

In [4]:
array.shape

(7,)

In [5]:
matrix01.shape

(3, 3)

In [6]:
matrix02.shape

(3, 3)

In [7]:
matrix03 = matrix01 + matrix02

In [8]:
matrix01

array([[ 1,  2,  3],
       [ 5,  6,  8],
       [ 9, 10, 11]])

In [9]:
matrix02

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]])

In [10]:
matrix03

array([[ 1,  2,  3],
       [ 7,  8, 10],
       [10, 11, 12]])

In [11]:
matrix01.shape[1]

3

In [12]:
ceros = np.zeros((5,3))

In [13]:
ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
def sumaMatrix(A,B):
  if(A.shape == B.shape):
    C = np.zeros(A.shape)
    for i in range(A.shape[0]):
      for j in range(A.shape[1]):
        C[i][j] = A[i][j] + B[i][j]
    return C
  else:
    print("Dimensiones No Coinciden")


In [15]:
def restaMatrix(A,B):
  if(A.shape == B.shape):
    C = np.zeros(A.shape)
    for i in range(A.shape[0]):
      for j in range(A.shape[1]):
        C[i][j] = A[i][j] - B[i][j]
    return C
  else:
    print("Dimensiones No Coinciden")

In [16]:
sumaMatrix(matrix01,matrix02)

array([[ 1.,  2.,  3.],
       [ 7.,  8., 10.],
       [10., 11., 12.]])

In [17]:
def mulMatrix(A,B):
  if(A.shape[1] == B.shape[0]):
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(C.shape[0]):
      for j in range(C.shape[1]):
        for k in range(A.shape[1]):
          C[i][j] += A[i][k]*B[k][j] 
    return C
  else:
    print("No esta definida la multiplicación para estas dimensiones")

In [18]:
def mulMatrix2(A,B):
  if(A.shape[1] == B.shape[0]):
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(C.shape[0]):
      for j in range(C.shape[1]):
          C[i][j] = (A[i]*B.T[j]).sum()   
    return C
  else:
    print("No esta definida la multiplicación para estas dimensiones")

In [19]:
matrix04 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
matrix04.shape

(3, 3)

In [21]:
matrix04[1].sum()

15

In [22]:
matrix04[2]* matrix04[0]

array([ 7, 16, 27])

In [23]:
matrix04T = matrix04.T

In [24]:
matrix04T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
mulMatrix2(matrix01,matrix02)

array([[ 7.,  7.,  7.],
       [20., 20., 20.],
       [31., 31., 31.]])

In [26]:
mulMatrix(matrix01,matrix02)

array([[ 7.,  7.,  7.],
       [20., 20., 20.],
       [31., 31., 31.]])

In [27]:
np.matmul(matrix01,matrix02)

array([[ 7,  7,  7],
       [20, 20, 20],
       [31, 31, 31]])

**Solución de Tarea**

In [28]:
m01 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m02 = np.array([[4,0,3],[2,3,0],[0,1,2]])
m03 = np.array([[0,0,1],[1,0,0],[0,1,0]])
m04 = np.array([[0,0,1],[1,1,1],[1,1,1]])
m05 = np.array([[0,0,1],[1,0,0],[0,1,0]])

In [29]:
sumaMatrix(  sumaMatrix(sumaMatrix(sumaMatrix(m01,m02),m03),m04),m05)

array([[ 5.,  2.,  9.],
       [ 9.,  9.,  7.],
       [ 8., 12., 12.]])

In [30]:
sumaMatrix(restaMatrix(restaMatrix( sumaMatrix(m01,m02),m03),m04),m05)

array([[ 5.,  2.,  5.],
       [ 5.,  7.,  5.],
       [ 6.,  8., 10.]])

In [31]:
def determiante2x2(A):
  if(A.shape == (2,2)):
    return A[0][0]* A[1][1] - A[0][1] *A[1][0]
  else:
    return print("No es del rango solicitado")

In [32]:
m06 = np.array([[10,22],[15,5]])

In [33]:
determiante2x2(m06)

-280

In [34]:
determiante2x2(m01)

No es del rango solicitado


In [35]:
a = ("hola","mundo")
b =(1,2,3,4)

In [36]:
def determiante3x3(A):
  if(A.shape == (3,3)):
    return A[0][0] * determiante2x2(np.delete(np.delete(A,0,0),0,1)) - A[0][1] * determiante2x2(np.delete(np.delete(A,0,0),1,1)) + A[0][2] * determiante2x2(np.delete(np.delete(A,0,0),2,1)) 
  else:
    print("Introduzca una matriz de 3x3")


In [37]:
determiante3x3(m01)

0

**¿Cómo obtener matrices Reducidas**

In [38]:
m01

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
m01_reducida11 = np.delete(np.delete(m01,0,0),0,1)
m01_reducida11

array([[5, 6],
       [8, 9]])

In [40]:
m01_reducida22 = np.delete(np.delete(m01,1,0),1,1)
m01_reducida22

array([[1, 3],
       [7, 9]])

In [41]:
m01_reducida31 = np.delete(np.delete(m01,2,0),0,1)
m01_reducida31

array([[2, 3],
       [5, 6]])

**PAR O IMPAR**

In [42]:
4%3

1

In [43]:
def par_impar(a):
  if(a%2 == 0):
    return print("Es Par")
  elif(a%2 ==1 ):
    return print("Es impar")

In [44]:
par_impar(19382741)

Es impar


In [45]:
def par_impar_matriz(i,j):
  if( (i+j)%2 == 0):
    return 1
  elif( (i+j)%2 == 1 ):
    return -1



In [46]:
par_impar_matriz(30,27)

-1

In [47]:
##Función que Calcula la matriz de Cofactores de A de 3x3
def cof(A):
  if(A.shape == (3,3)):
    C = np.zeros((3,3))
    for i in range(C.shape[0]):
      for j in range(C.shape[1]):
        matriz_disminuda = np.delete(np.delete(A,i,0),j,1)
        det_i_j = determiante2x2(matriz_disminuda)
        signo = par_impar_matriz(i,j)
        C[i][j]= signo * det_i_j 
    return C
  else:
    return print("Introduce una matriz de 3x3")

In [48]:
cof(m01)

array([[ -3.,   6.,  -3.],
       [  6., -12.,   6.],
       [ -3.,   6.,  -3.]])

In [49]:
## Calcular la matriz adjunta de A de dimension 3x3
def adj(A):
  if(A.shape == (3,3)): 
    return cof(A).T
  else:
    return print("Introduce una matriz de 3x3")

In [50]:
m02

array([[4, 0, 3],
       [2, 3, 0],
       [0, 1, 2]])

In [51]:
cof(m02)

array([[ 6., -4.,  2.],
       [ 3.,  8., -4.],
       [-9.,  6., 12.]])

In [52]:
adj(m02)

array([[ 6.,  3., -9.],
       [-4.,  8.,  6.],
       [ 2., -4., 12.]])

In [53]:
##Calcular la matriz inversa de una matriz a de 3x3
def inv(A):
  if(A.shape ==(3,3)):
    return (1/ determiante3x3(A)) * adj(A)
  else:
    return print("Introduce una matriz de 3x3")

In [54]:
inv(m02)

array([[ 0.2       ,  0.1       , -0.3       ],
       [-0.13333333,  0.26666667,  0.2       ],
       [ 0.06666667, -0.13333333,  0.4       ]])

In [55]:
mulMatrix(m02,inv(m02))

array([[1.00000000e+00, 0.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])