<a href="https://colab.research.google.com/github/SirCarlitros/Math3/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5,6,7])

In [4]:
matrix01 = np.array([[1,2,3],[5,6,8],[9,10,11]])
matrix02 = np.array([[0,0,0],[2,2,2],[1,1,1]])

In [5]:
array.shape

(7,)

In [6]:
matrix01.shape

(3, 3)

In [7]:
matrix02.shape

(3, 3)

In [8]:
matrix03 = matrix01 + matrix02

In [9]:
matrix01

array([[ 1,  2,  3],
       [ 5,  6,  8],
       [ 9, 10, 11]])

In [10]:
matrix02

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]])

In [11]:
matrix03

array([[ 1,  2,  3],
       [ 7,  8, 10],
       [10, 11, 12]])

In [12]:
matrix01.shape[1]

3

In [13]:
ceros = np.zeros((5,3))

In [14]:
ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
def sumaMatrix(A,B):
  if(A.shape == B.shape):
    C = np.zeros(A.shape)
    for i in range(A.shape[0]):
      for j in range(A.shape[1]):
        C[i][j] = A[i][j] + B[i][j]
    return C
  else:
    print("Dimensiones No Coinciden")


In [43]:
def restaMatrix(A,B):
  if(A.shape == B.shape):
    C = np.zeros(A.shape)
    for i in range(A.shape[0]):
      for j in range(A.shape[1]):
        C[i][j] = A[i][j] - B[i][j]
    return C
  else:
    print("Dimensiones No Coinciden")

In [16]:
sumaMatrix(matrix01,matrix02)

array([[ 1.,  2.,  3.],
       [ 7.,  8., 10.],
       [10., 11., 12.]])

In [17]:
def mulMatrix(A,B):
  if(A.shape[1] == B.shape[0]):
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(C.shape[0]):
      for j in range(C.shape[1]):
        for k in range(A.shape[1]):
          C[i][j] += A[i][k]*B[k][j] 
    return C
  else:
    print("No esta definida la multiplicación para estas dimensiones")

In [18]:
def mulMatrix2(A,B):
  if(A.shape[1] == B.shape[0]):
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(C.shape[0]):
      for j in range(C.shape[1]):
          C[i][j] = (A[i]*B.T[j]).sum()   
    return C
  else:
    print("No esta definida la multiplicación para estas dimensiones")

In [19]:
matrix04 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
matrix04.shape

(3, 3)

In [21]:
matrix04[1].sum()

15

In [22]:
matrix04[2]* matrix04[0]

array([ 7, 16, 27])

In [23]:
matrix04T = matrix04.T

In [24]:
matrix04T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [25]:
mulMatrix2(matrix01,matrix02)

array([[ 7.,  7.,  7.],
       [20., 20., 20.],
       [31., 31., 31.]])

In [26]:
mulMatrix(matrix01,matrix02)

array([[ 7.,  7.,  7.],
       [20., 20., 20.],
       [31., 31., 31.]])

In [27]:
np.matmul(matrix01,matrix02)

array([[ 7,  7,  7],
       [20, 20, 20],
       [31, 31, 31]])

**Solución de Tarea**

In [41]:
m01 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m02 = np.array([[4,0,3],[2,3,0],[0,1,2]])
m03 = np.array([[0,0,1],[1,0,0],[0,1,0]])
m04 = np.array([[0,0,1],[1,1,1],[1,1,1]])
m05 = np.array([[0,0,1],[1,0,0],[0,1,0]])

In [42]:
sumaMatrix(  sumaMatrix(sumaMatrix(sumaMatrix(m01,m02),m03),m04),m05)

array([[ 5.,  2.,  9.],
       [ 9.,  9.,  7.],
       [ 8., 12., 12.]])

In [34]:
resultado

array([[ 5.,  2.,  7.],
       [ 7.,  8.,  6.],
       [ 7., 10., 11.]])

In [47]:
sumaMatrix(restaMatrix(restaMatrix( sumaMatrix(m01,m02),m03),m04),m05)

array([[ 5.,  2.,  5.],
       [ 5.,  7.,  5.],
       [ 6.,  8., 10.]])

In [49]:
def determiante2x2(A):
  return A[0][0]* A[1][1] - A[0][1] *A[1][0]

In [50]:
m06 = np.array([[10,22],[15,5]])

In [52]:
determiante2x2(m06)

-280