<a href="https://colab.research.google.com/github/SirCarlitros/Math3/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array = np.array([1,2,3,4,5,6,7])

In [ ]:
matrix01 = np.array([[1,2,3],[5,6,8],[9,10,11]])
matrix02 = np.array([[0,0,0],[2,2,2],[1,1,1]])

In [ ]:
array.shape

(7,)

In [ ]:
matrix01.shape

(3, 3)

In [ ]:
matrix02.shape

(3, 3)

In [ ]:
matrix03 = matrix01 + matrix02

In [ ]:
matrix01

array([[ 1,  2,  3],
       [ 5,  6,  8],
       [ 9, 10, 11]])

In [ ]:
matrix02

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]])

In [ ]:
matrix03

array([[ 1,  2,  3],
       [ 7,  8, 10],
       [10, 11, 12]])

In [ ]:
matrix01.shape[1]

3

In [ ]:
ceros = np.zeros((5,3))

In [ ]:
ceros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
def sumaMatrix(A,B):
  if(A.shape == B.shape):
    C = np.zeros(A.shape)
    for i in range(A.shape[0]):
      for j in range(A.shape[1]):
        C[i][j] = A[i][j] + B[i][j]
    return C
  else:
    print("Dimensiones No Coinciden")


In [ ]:
sumaMatrix(matrix01,matrix02)

array([[ 1.,  2.,  3.],
       [ 7.,  8., 10.],
       [10., 11., 12.]])

In [ ]:
def mulMatrix(A,B):
  if(A.shape[1] == B.shape[0]):
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(C.shape[0]):
      for j in range(C.shape[1]):
        for k in range(A.shape[1]):
          C[i][j] += A[i][k]*B[k][j] 
    return C
  else:
    print("No esta definida la multiplicación para estas dimensiones")

In [ ]:
def mulMatrix2(A,B):
  if(A.shape[1] == B.shape[0]):
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(C.shape[0]):
      for j in range(C.shape[1]):
          C[i][j] = (A[i]*B.T[j]).sum()   
    return C
  else:
    print("No esta definida la multiplicación para estas dimensiones")

In [ ]:
matrix04 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
matrix04.shape

(3, 3)

In [ ]:
matrix04[1].sum()

15

In [ ]:
matrix04[2]* matrix04[0]

array([ 7, 16, 27])

In [ ]:
matrix04T = matrix04.T

In [ ]:
matrix04T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
mulMatrix2(matrix01,matrix02)

array([[ 7.,  7.,  7.],
       [20., 20., 20.],
       [31., 31., 31.]])

In [ ]:
mulMatrix(matrix01,matrix02)

array([[ 7.,  7.,  7.],
       [20., 20., 20.],
       [31., 31., 31.]])

In [ ]:
np.matmul(matrix01,matrix02)

array([[ 7,  7,  7],
       [20, 20, 20],
       [31, 31, 31]])